---
format: 
  beamer:
    theme: AAUsimple
    fontsize: 8pt
    header-includes: |
      \title{Introduktion til R}
      \date{7. februar 2023}
      \author{Kristian G. Kjelmann (\href{mailto:kgk@socsci.aau.dk}{{\tt kgk@socsci.aau.dk}})\\
              \&\\
              Rolf L. Lund (\href{mailto:rolfll@socsci.aau.dk}{{\tt rolfll@socsci.aau.dk}})
              }
      \begin{document}
editor: visual
execute:
  echo: true
  warning: false
  error: true
---

## ØVELSE 1

1.  Dan et subset af data, der *kun* indeholder mænd født efter 1975 og med følgende variable: `idno`, `gndr`, `yrbrn`, `netustm`, `lvpntyr`.

2.  Beregn middelværdien for tid brugt på internettet om dagen (`netustm`) for subsettet.

3.  Tilføj en aldersvariabel til subsettet (datasættet er fra 2018).

4.  Tilføj en variabel til subsettet, der indeholder antal år respondenten boede hjemme, inden de flyttede hjemmefra (`lvpntyr`: first time living separately for 2 months).

-   Bemærk at variablen `lvpntyr` muligvis ikke er klar til beregninger med det samme.

-   Husk at `as.numeric()` tvinger værdier om til tal.

5.  Hvad er det maksimale antal år, en respondent i subsettet har boet hjemme? (brug enten `summary()` eller `max()`).

6.  Hvor gammel er personen, som har boet hjemme længst?

## ØVELSE 2

1.  Skriv din kodefil ren, så den *kun* indeholder indlæsning af data, filtreringen og udvælgelse af variable fra øvelse 1 samt variable dannet fra øvelse 2.

2.  Overvej hvad du kan gøre, for at gøre din kode mere læsbar (indsæt kommentarer, tilføj afsnit osv.). Tilret din kode herefeter.

3.  Læg din kodefil på moodle ("Kodefiler hold B").

## ØVELSE 3 (fælles)

Vi har modtaget en kodefil, som danner et subset af ESS18 data samt danner variabel for alder samt variabel for, hvor meget man arbejder mere end man er ansat til (overarbejde).

1.  Find ud af hvad subsettet indeholder ved at kigge på kodefilen *uden at køre den!*.

2.  Find ud af hvad der skal tilrettes for, at koden virker på din egen computer.

3.  Find ud af hvilke linjer kode der skal tilføjes, for at vi kan se alder for den person, som har mest overarbejde.
